version: '3.1'

services:
  backend:
    image: app/backend
    build:
      dockerfile: ./dockerfile.dev
      context: .
      depends_on:
        - mongodb
        - cache
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb_dipl
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongodb:/data/db
  cache:
    image: redis:6.2-alpine
    container_name: cache_dipl
    restart: always
    ports:
      - '6379:6379'
volumes:
  mongodb: